In [2]:
import torch

张量表示一个数值组成的数组，这个数组可能拥有多个维度

In [3]:
x=torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 张量的shape属性能够访问张量的形状和张量内的元素总数

In [4]:
x.shape

torch.Size([10])

In [5]:
x.numel() ##表示张量内的元素数量，是一个标量

10

要改变一个张量的形状而不改变张量内的元素的数量和数值需要调用reshape函数

In [6]:
x.reshape(5,2) ##将张量改为5行2列

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

可以生成一些全是1、全是0或是从特定分布中随机采样的张量

In [7]:
torch.zeros((3,4,5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [8]:
torch.ones((3,4,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

常见的标准运算都能升级成按元素计算

In [9]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [10]:
##指数计算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

连接多个张量

In [11]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,1,2,3]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  1.,  2.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  1.,  2.,  3.]]))

使用逻辑运算符构建二元张量

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对一个张量中的所有元素求和会产生只有一个元素的张量

In [13]:
X.sum()

tensor(66.)

面对不同形状的张量运算，可使用广播机制来执行按位操作，结果张量的shape为每个张量的shape对应位置取最大值。

In [14]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
c = a + b
c

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [17]:
c.shape

torch.Size([3, 2])

元素的访问：用[-1]访问最后一个元素，用[1:3]访问第一个和第二个元素

In [19]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

通过索引改变张量内的元素数值

In [22]:
X[1,2]=7
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  7.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值，只需要索引所有元素，然后赋值

In [23]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

pytorch张量转为NumPy张量

In [26]:
A=X.numpy()
B=torch.tensor(A)
A,B
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将张量转为python标量

In [28]:
C = torch.tensor(3.5)
C,C.item(),float(C),int(C)

(tensor(3.5000), 3.5, 3.5, 3)

创建一个csv数据集

In [34]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house.csv')

with open(data_file,'w') as f:
    f.write('NumRooms,Name,Prince\n')
    f.write('NA,Alice,256000\n')
    f.write('3,NA,NA\n')
    f.write('5,Dave,362110\n')
    f.write('NA,Alex,NA\n')

使用pandas读取数据集

In [37]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms   Name    Prince
0       NaN  Alice  256000.0
1       3.0    NaN       NaN
2       5.0   Dave  362110.0
3       NaN   Alex       NaN

通过插值和删除来处理缺失值

In [39]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
inputs

C:\Users\pod2g\AppData\Local\Temp\ipykernel_7636\3505320478.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


NumRooms   Name
0       4.0  Alice
1       3.0    NaN
2       5.0   Dave
3       4.0   Alex

对于数据集中的离散值或是类别值，可以将Na视为一个类别

In [40]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Name_Alex  Name_Alice  Name_Dave  Name_nan
0       4.0          0           1          0         0
1       3.0          0           0          0         1
2       5.0          0           0          1         0
3       4.0          1           0          0         0

在将数据集中的数据都转化为数值后，可以将这些数值转化为tensor张量

In [41]:
X, y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X, y

(tensor([[4., 0., 1., 0., 0.],
         [3., 0., 0., 0., 1.],
         [5., 0., 0., 1., 0.],
         [4., 1., 0., 0., 0.]], dtype=torch.float64),
 tensor([256000.,     nan, 362110.,     nan], dtype=torch.float64))