In [1]:
import torch

假设现在要对y=2**x** <sup>T</sup> **x** 中的**x**向量求导

先声明一个**x**向量

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

在计算梯度（求导）之前，需要一个地方来储存梯度

In [6]:
x.requires_grad_(True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

计算y

In [7]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

调用反向传播函数来自动计算y关于x每个分量的梯度

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

pytorch自动求导时会累积梯度，因此在计算另一个x的函数时，需要对之前的梯度清零。

In [9]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])